# Tech Layoffs 2026 Analysis

## Introduction

The tech industry has experienced significant workforce changes in 2026, with companies across various sectors implementing layoffs for different reasons. In this workshop, you'll analyze real-world data tracking tech layoffs from Q1 2026.

Your goal is to explore patterns in the data, understand which sectors and countries are most affected, investigate the role of AI in layoff decisions, and derive insights about company strategies during this period.

You'll use the `tech_layoffs_2026_tracker.csv` dataset, where each row represents a layoff event at a specific company.

**Dataset location:** `../data/tech_layoffs_2026_tracker.csv`

## Setup: Import Libraries and Load Data

Start by importing pandas and loading the dataset into a DataFrame called `layoffs`.

In [ ]:
# Import pandas
import pandas as pd

# Load the data from '../data/tech_layoffs_2026_tracker.csv' into a DataFrame called 'layoffs'
layoffs = pd.read_csv('tech_layoffs_2026_tracker.csv')

## Part 1: Initial Data Exploration

Before diving into analysis, get familiar with the dataset structure, size, and quality.

### Task 1.1: Preview and Understand the Data

Examine the first several rows of the dataset. Then determine:
- How many rows (layoff events) and columns are in the dataset?
- What data types are present in each column?
- Are there any missing values?

*Hint: Consider using `.head()`, `.shape`, and `.info()`*

In [ ]:
# Preview the data and explore its structure
display(layoffs.head(28))

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"
5,Salesforce,2026-01-10,1000,1.4,CRM/SaaS,USA,San Francisco,True,AI-driven efficiency and restructuring,37.9,...,1000,1000,NetworkWorld / Bloomberg,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.39,"March 18, 2026"
6,Autodesk,2026-01-25,1000,9.0,Design Software,USA,San Francisco,False,Post-Ansys acquisition restructuring,5.9,...,500,1200,NetworkWorld,January 2026,Q1 2026,North America,Medium (500-2K),Positive,9.09,"March 18, 2026"
7,eBay,2026-01-28,800,5.0,E-Commerce,USA,San Jose,True,AI-forward strategy in customer ops,10.3,...,1000,1000,NetworkWorld,January 2026,Q1 2026,North America,Medium (500-2K),Positive,7.27,"March 18, 2026"
8,Pinterest,2026-02-10,675,4.0,Social Media,USA,San Francisco,True,AI-forward content and marketing strategy,3.6,...,1500,200,NetworkWorld,February 2026,Q1 2026,North America,Medium (500-2K),Positive,18.24,"March 18, 2026"
9,Ericsson,2026-01-15,1600,12.0,Telecommunications,Sweden,Stockholm,False,Declining 5G demand and cost reduction,24.3,...,3000,5000,InformationWeek / FierceNetwork,January 2026,Q1 2026,Europe,Medium (500-2K),Positive,1.52,"March 18, 2026"
10,ASML,2026-01-20,1700,3.4,Semiconductors,Netherlands,Veldhoven,False,Chip market slowdown,30.8,...,0,0,NetworkWorld,January 2026,Q1 2026,Europe,Medium (500-2K),Negative,4.05,"March 18, 2026"
11,ams OSRAM,2026-02-05,2000,12.0,Semiconductors,Austria,Premstaetten,False,Cost restructuring and portfolio focus,3.2,...,0,500,NetworkWorld,February 2026,Q1 2026,Europe,Medium (500-2K),Positive,9.52,"March 18, 2026"
12,Ocado,2026-01-30,1000,7.0,Grocery Tech,UK,Hatfield,True,AI automation in warehouse operations,3.8,...,0,0,NetworkWorld,January 2026,Q1 2026,Europe,Medium (500-2K),Positive,7.14,"March 18, 2026"
13,WiseTech Global,2026-02-20,2000,25.0,Logistics Software,Australia,Sydney,True,AI replaces QA and testing teams,3.2,...,0,0,Medha Cloud,February 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,25.00,"March 18, 2026"
14,Cisco,2026-02-15,6000,7.0,Networking/Cybersecurity,USA,San Jose,False,Restructuring after Splunk acquisition,56.9,...,4200,6000,Computerworld,February 2026,Q1 2026,North America,Mega (5K+),Negative,7.06,"March 18, 2026"
15,T-Mobile,2026-02-02,363,0.1,Telecommunications,USA,Bellevue,False,Restructuring sales teams,80.0,...,0,5000,FierceNetwork,February 2026,Q1 2026,North America,Small (<500),Negative,0.51,"March 18, 2026"
16,SK Battery America,2026-03-16,958,37.3,EV Batteries,USA,Commerce GA,False,Slowing EV demand,8.4,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,37.33,"March 18, 2026"
17,Walgreens,2026-03-11,1000,0.5,Retail Pharmacy,USA,Deerfield IL,False,Store closures and cost restructuring,140.0,...,3000,2000,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,0.32,"March 18, 2026"
18,Telefonica,2026-01-15,5000,5.0,Telecommunications,Spain,Madrid,False,Cost restructuring with compensation,44.5,...,0,3000,FierceNetwork,January 2026,Q1 2026,Europe,Large (2K-5K),Positive,5.00,"March 18, 2026"
19,xAI,2026-02-25,50,2.0,AI Research,USA,San Francisco,True,Internal reorganization,0.0,...,0,0,TechCrunch,February 2026,Q1 2026,North America,Small (<500),Neutral,2.00,"March 18, 2026"
20,Palo Alto Networks,2026-02-18,500,2.0,Cybersecurity,USA,Santa Clara,False,Post-CyberArk acquisition overlap,8.0,...,0,500,InformationWeek,February 2026,Q1 2026,North America,Small (<500),Positive,3.33,"March 18, 2026"
21,Livspace,2026-02-10,1000,15.0,Interior Design Tech,India,Bangalore,True,AI design tools replace human designers,0.3,...,0,0,Medha Cloud,February 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Neutral,14.29,"March 18, 2026"
22,General Motors Tech,2026-01-22,1000,2.0,Automotive Tech,USA,Detroit,False,Rethinking digital transformation,180.0,...,500,1500,Computerworld,January 2026,Q1 2026,North America,Medium (500-2K),Negative,0.67,"March 18, 2026"
23,Workday,2026-01-28,2200,8.5,Enterprise SaaS,USA,Pleasanton CA,True,AI investment and office space reduction,8.5,...,1750,1750,Computerworld,January 2026,Q1 2026,North America,Large (2K-5K),Positive,8.53,"March 18, 2026"
24,Ergo Insurance,2026-03-01,200,2.0,Insurance,Germany,Dusseldorf,True,AI automates insurance tasks,0.0,...,0,0,Intellizence,March 2026,Q1 2026,Europe,Small (<500),Neutral,2.22,"March 18, 2026"
25,Algoma Steel,2026-03-07,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"
26,Meta Platforms (Planned),2026-03-13,16000,20.0,Social Media/AI,USA,Menlo Park,True,Offset AI infrastructure costs,164.5,...,0,0,CNBC / Reuters / IBTimes,March 2026,Q1 2026,North America,Mega (5K+),Positive,20.25,"March 18, 2026"
27,Algoma Steel,2026-03-23,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure effective,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"

### Task 1.2: Basic Statistics

Get a statistical summary of the numerical columns in the dataset. What do you notice about the distribution of jobs cut, percentage of workforce cut, and company revenues?

*Hint: The `.describe()` method provides summary statistics*

In [ ]:
# Generate summary statistics
layoffs.describe()

,jobs_cut,pct_workforce_cut,company_revenue_2025_bn,pre_layoff_headcount,stock_change_day_pct,simultaneous_ai_investment_bn,layoffs_2024,layoffs_2025,laid_off_vs_headcount_pct
count,28.000000,28.000000,28.00000,2.800000e+01,28.000000,28.000000,28.000000,28.000000,28.000000
mean,3612.357143,10.639286,63.62500,1.076631e+05,0.832143,14.046429,944.642857,1951.785714,10.452143
std,6546.591373,10.433505,139.44986,2.915339e+05,1.742721,34.751824,1615.511574,3328.482085,10.719330
min,50.000000,0.100000,0.00000,2.500000e+03,-2.100000,0.000000,0.000000,0.000000,0.320000
25%,989.500000,2.525000,3.50000,8.750000e+03,-0.325000,0.000000,0.000000,0.000000,1.975000
50%,1000.000000,7.750000,9.40000,1.850000e+04,0.650000,0.450000,0.000000,500.000000,7.205000
75%,2050.000000,15.000000,53.90000,8.050000e+04,1.850000,2.250000,1125.000000,1812.500000,15.810000
max,30000.000000,40.000000,716.90000,1.550000e+06,5.800000,115.000000,6000.000000,14000.000000,40.000000

## Part 1.5: Boolean Filtering and DataFrame Manipulation

Before diving into complex analysis, let's practice essential DataFrame operations: filtering data based on conditions, selecting specific columns, and removing unwanted data.

### Task 1.3: Boolean Filtering - AI-Cited Layoffs

Filter the dataset to show only layoffs where AI was explicitly cited as a reason (`ai_cited == True`).

Questions:
- How many layoff events cited AI?
- What's the total number of jobs cut in AI-related layoffs?

*Hint: Use boolean indexing like `df[df['column'] == value]`*

In [ ]:
# Filter for AI-cited layoffs
ai_layoffs = layoffs[layoffs['ai_cited'] == True]

print(len(ai_layoffs))
print(f"Total jobs cut in AI-related layoffs: {ai_layoffs['jobs_cut'].sum():,}")



# Count and sum jobs cut

14
Total jobs cut in AI-related layoffs: 62,025

### Task 1.4: Multiple Conditions - Large US Tech Layoffs

Filter the dataset to find layoffs that meet ALL of these criteria:
- Country is USA
- Jobs cut is greater than 1,000
- Sector contains "Software", "Social Media", or "E-Commerce"

Which companies meet these criteria?

*Hint: Combine conditions with `&` (and) or `|` (or). Use `.isin()` for checking multiple values. Remember to wrap each condition in parentheses!*

In [ ]:
# Filter for large US tech layoffs
large_us_tech = layoffs[
    (layoffs['country'] == 'USA') &
    (layoffs['jobs_cut'] > 1000) &
    (layoffs['sector'].isin(['Enterprise', 'Social Media', 'E-Commerce/Cloud', 'Fintech', 'CRM/SaaS']))
]

print(f"Number of large US tech layoffs (>1000 jobs): {len(large_us_tech)}")

Number of large US tech layoffs (>1000 jobs): 2

### Task 1.5: Selecting Specific Columns

Create a new DataFrame called `layoffs_summary` that contains only these columns:
- `company`
- `jobs_cut`
- `pct_workforce_cut`
- `sector`
- `country`
- `ai_cited`

Use `.copy()` to ensure it's a true independent copy, not a view of the original data.

*Hint: Select columns using double brackets `df[['col1', 'col2']]` then chain `.copy()`*

In [ ]:
# Create layoffs_summary with selected columns

layoffs_summary = layoffs[['company', 'country', 'ai_cited', 'pct_workforce_cut', 'sector', 'jobs_cut']].copy()
# Preview the new DataFrame

print("Layoffs summary DataFrame:")
print(f"Shape: {layoffs_summary.shape}")
layoffs_summary.head(10)

Layoffs summary DataFrame:
Shape: (28, 6)

,company,country,ai_cited,pct_workforce_cut,sector,jobs_cut
0,Amazon,USA,False,2.7,E-Commerce/Cloud,16000
1,Block,USA,True,40.0,Fintech,4000
2,Meta Reality Labs,USA,True,10.0,Social Media/VR,1500
3,Atlassian,Australia,True,10.0,Enterprise Software,1600
4,Oracle,USA,True,15.0,Enterprise Software,30000
5,Salesforce,USA,True,1.4,CRM/SaaS,1000
6,Autodesk,USA,False,9.0,Design Software,1000
7,eBay,USA,True,5.0,E-Commerce,800
8,Pinterest,USA,True,4.0,Social Media,675
9,Ericsson,Sweden,False,12.0,Telecommunications,1600

### Task 1.6: Dropping Columns and Rows

Practice removing data you don't need:

**Part A:** Create a DataFrame called `layoffs_clean` that excludes these administrative columns:
- `data_as_of`
- `verified_source`
- `quarter`

**Part B:** From the full dataset, create a new DataFrame called `recent_layoffs` that excludes any rows where the month is "January 2026" (filter them out using boolean indexing).

*Hint: For Part A, use `.drop()` with `columns=` and `axis=1`. For Part B, use boolean filtering with `!=`*

In [ ]:
# Part A: Drop administrative columns
layoffs.drop(['data_as_of', 'verified_source', 'quarter'], axis=1)

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,roles_most_affected,replacement_roles,ceo_quote,layoffs_2024,layoffs_2025,month,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,"Middle management, program managers","AI engineers, data architects",Moving faster with fewer layers,4000,14000,January 2026,North America,Mega (5K+),Positive,1.03
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,"QA testers, customer support, content","AI prompt engineers, ML engineers",Smaller team using AI can do more,0,1000,February 2026,North America,Large (2K-5K),Positive,40.00
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,"VR/AR engineers, metaverse designers","AI researchers, LLM engineers",Redirecting investment toward AI R&D,0,500,January 2026,North America,Medium (500-2K),Positive,1.90
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,"R&D engineers, QA, IT ops","AI product managers, enterprise sales",Bar for great software companies has gone up,0,500,March 2026,Asia-Pacific,Medium (500-2K),Positive,10.00
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,"IT operations, database admins, support","AI infrastructure engineers, GPU specialists",Swapping workers for AI chips,6000,10000,February 2026,North America,Mega (5K+),Positive,15.00
5,Salesforce,2026-01-10,1000,1.4,CRM/SaaS,USA,San Francisco,True,AI-driven efficiency and restructuring,37.9,...,"Sales support, Tier-1 customer service",Agentforce AI specialists,AI handles routine tasks at scale,1000,1000,January 2026,North America,Medium (500-2K),Positive,1.39
6,Autodesk,2026-01-25,1000,9.0,Design Software,USA,San Francisco,False,Post-Ansys acquisition restructuring,5.9,...,Overlapping roles from merger,Cloud integration engineers,Realignment after Ansys acquisition,500,1200,January 2026,North America,Medium (500-2K),Positive,9.09
7,eBay,2026-01-28,800,5.0,E-Commerce,USA,San Jose,True,AI-forward strategy in customer ops,10.3,...,"Content moderation, customer support",AI content reviewers,AI handles majority of support tickets,1000,1000,January 2026,North America,Medium (500-2K),Positive,7.27
8,Pinterest,2026-02-10,675,4.0,Social Media,USA,San Francisco,True,AI-forward content and marketing strategy,3.6,...,"Content moderation, marketing roles",AI content specialists,Investing in AI-native workflows,1500,200,February 2026,North America,Medium (500-2K),Positive,18.24
9,Ericsson,2026-01-15,1600,12.0,Telecommunications,Sweden,Stockholm,False,Declining 5G demand and cost reduction,24.3,...,"Network engineers, R&D staff",None announced,Operational efficiency initiatives,3000,5000,January 2026,Europe,Medium (500-2K),Positive,1.52
10,ASML,2026-01-20,1700,3.4,Semiconductors,Netherlands,Veldhoven,False,Chip market slowdown,30.8,...,"Manufacturing support, admin roles",None announced,Aligning workforce with market demand,0,0,January 2026,Europe,Medium (500-2K),Negative,4.05
11,ams OSRAM,2026-02-05,2000,12.0,Semiconductors,Austria,Premstaetten,False,Cost restructuring and portfolio focus,3.2,...,"Manufacturing, engineering support",None announced,Restructuring to improve profitability,0,500,February 2026,Europe,Medium (500-2K),Positive,9.52
12,Ocado,2026-01-30,1000,7.0,Grocery Tech,UK,Hatfield,True,AI automation in warehouse operations,3.8,...,"Warehouse supervisors, logistics","Robotics engineers, AI ops",AI-driven warehouse automation,0,0,January 2026,Europe,Medium (500-2K),Positive,7.14
13,WiseTech Global,2026-02-20,2000,25.0,Logistics Software,Australia,Sydney,True,AI replaces QA and testing teams,3.2,...,"QA engineers, manual testers",AI test automation engineers,AI tools handle testing workflows,0,0,February 2026,Asia-Pacific,Medium (500-2K),Positive,25.00
14,Cisco,2026-02-15,6000,7.0,Networking/Cybersecurity,USA,San Jose,False,Restructuring after Splunk acquisition,56.9,...,Overlapping roles post-acquisition,Security AI specialists,Realigning global workforce,4200,6000,February 2026,North America,Mega (5K+),Negative,7.06
15,T-Mobile,2026-02-02,363,0.1,Telecommunications,USA,Bellevue,False,Restructuring sales teams,80.0,...,Sales representatives,None announced,Reorganizing under new CEO,0,5000,February 2026,North America,Small (<500),Negative,0.51
16,SK Battery America,2026-03-16,958,37.3,EV Batteries,USA,Commerce GA,False,Slowing EV demand,8.4,...,Battery production workers,None announced,EV market slowdown,0,0,March 2026,North America,Medium (500-2K),Negative,37.33
17,Walgreens,2026-03-11,1000,0.5,Retail Pharmacy,USA,Deerfield IL,False,Store closures and cost restructuring,140.0,...,"Pharmacy staff, store associates",None announced,Streamlining operations,3000,2000,March 2026,North America,Medium (500-2K),Negative,0.32
18,Telefonica,2026-01-15,5000,5.0,Telecommunications,Spain,Madrid,False,Cost restructuring with compensation,44.5,...,Legacy network operations,Digital roles,Voluntary redundancy offered,0,3000,January 2026,Europe,Large (2K-5K),Positive,5.00
19,xAI,2026-02-25,50,2.0,AI Research,USA,San Francisco,True,Internal reorganization,0.0,...,"Senior engineers, co-founders",None announced,Reorganization confirmed by Musk,0,0,February 2026,North America,Small (<500),Neutral,2.00
20,Palo Alto Networks,2026-02-18,500,2.0,Cybersecurity,USA,Santa Clara,False,Post-CyberArk acquisition overlap,8.0,...,Overlapping roles from merger,None announced,Eliminating post-acquisition redundancies,0,500,February 2026,North America,Small (<500),Positive,3.33
21,Livspace,2026-02-10,1000,15.0,Interior Design Tech,India,Bangalore,True,AI design tools replace human designers,0.3,...,"Interior designers, project managers",AI design specialists,AI-driven design automation,0,0,February 2026,Asia-Pacific,Medium (500-2K),Neutral,14.29
22,General Motors Tech,2026-01-22,1000,2.0,Automotive Tech,USA,Detroit,False,Rethinking digital transformation,180.0,...,"Software engineers, digital staff",None announced,Moving resources to highest-priority work,500,1500,January 2026,North America,Medium (500-2K),Negative,0.67
23,Workday,2026-01-28,2200,8.5,Enterprise SaaS,USA,Pleasanton CA,True,AI investment and office space reduction,8.5,...,"Customer service, admin roles",AI success managers,Investing more in AI and international,1750,1750,January 2026,North America,Large (2K-5K),Positive,8.53
24,Ergo Insurance,2026-03-01,200,2.0,Insurance,Germany,Dusseldorf,True,AI automates insurance tasks,0.0,...,"Claims processors, underwriters",AI system trainers,AI automates traditional insurance tasks,0,0,March 2026,Europe,Small (<500),Neutral,2.22
25,Algoma Steel,2026-03-07,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure,2.8,...,Steel production workers,None announced,Closing blast furnace operations,0,0,March 2026,North America,Medium (500-2K),Negative,20.00
26,Meta Platforms (Planned),2026-03-13,16000,20.0,Social Media/AI,USA,Menlo Park,True,Offset AI infrastructure costs,164.5,...,"Engineering, middle management, ops","AI engineers, GPU infrastructure",Building personal superintelligence,0,0,March 2026,North America,Mega (5K+),Positive,20.25
27,Algoma Steel,2026-03-23,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure effective,2.8,...,Steel workers,None announced,Effective layoff date per filing,0,0,March 2026,North America,Medium (500-2K),Negative,20.00

In [ ]:
# Part B: Filter out January 2026 layoffs
layoffs[layoffs['month'] != "January 2026"]

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"
8,Pinterest,2026-02-10,675,4.0,Social Media,USA,San Francisco,True,AI-forward content and marketing strategy,3.6,...,1500,200,NetworkWorld,February 2026,Q1 2026,North America,Medium (500-2K),Positive,18.24,"March 18, 2026"
11,ams OSRAM,2026-02-05,2000,12.0,Semiconductors,Austria,Premstaetten,False,Cost restructuring and portfolio focus,3.2,...,0,500,NetworkWorld,February 2026,Q1 2026,Europe,Medium (500-2K),Positive,9.52,"March 18, 2026"
13,WiseTech Global,2026-02-20,2000,25.0,Logistics Software,Australia,Sydney,True,AI replaces QA and testing teams,3.2,...,0,0,Medha Cloud,February 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,25.00,"March 18, 2026"
14,Cisco,2026-02-15,6000,7.0,Networking/Cybersecurity,USA,San Jose,False,Restructuring after Splunk acquisition,56.9,...,4200,6000,Computerworld,February 2026,Q1 2026,North America,Mega (5K+),Negative,7.06,"March 18, 2026"
15,T-Mobile,2026-02-02,363,0.1,Telecommunications,USA,Bellevue,False,Restructuring sales teams,80.0,...,0,5000,FierceNetwork,February 2026,Q1 2026,North America,Small (<500),Negative,0.51,"March 18, 2026"
16,SK Battery America,2026-03-16,958,37.3,EV Batteries,USA,Commerce GA,False,Slowing EV demand,8.4,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,37.33,"March 18, 2026"
17,Walgreens,2026-03-11,1000,0.5,Retail Pharmacy,USA,Deerfield IL,False,Store closures and cost restructuring,140.0,...,3000,2000,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,0.32,"March 18, 2026"
19,xAI,2026-02-25,50,2.0,AI Research,USA,San Francisco,True,Internal reorganization,0.0,...,0,0,TechCrunch,February 2026,Q1 2026,North America,Small (<500),Neutral,2.00,"March 18, 2026"
20,Palo Alto Networks,2026-02-18,500,2.0,Cybersecurity,USA,Santa Clara,False,Post-CyberArk acquisition overlap,8.0,...,0,500,InformationWeek,February 2026,Q1 2026,North America,Small (<500),Positive,3.33,"March 18, 2026"
21,Livspace,2026-02-10,1000,15.0,Interior Design Tech,India,Bangalore,True,AI design tools replace human designers,0.3,...,0,0,Medha Cloud,February 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Neutral,14.29,"March 18, 2026"
24,Ergo Insurance,2026-03-01,200,2.0,Insurance,Germany,Dusseldorf,True,AI automates insurance tasks,0.0,...,0,0,Intellizence,March 2026,Q1 2026,Europe,Small (<500),Neutral,2.22,"March 18, 2026"
25,Algoma Steel,2026-03-07,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"
26,Meta Platforms (Planned),2026-03-13,16000,20.0,Social Media/AI,USA,Menlo Park,True,Offset AI infrastructure costs,164.5,...,0,0,CNBC / Reuters / IBTimes,March 2026,Q1 2026,North America,Mega (5K+),Positive,20.25,"March 18, 2026"
27,Algoma Steel,2026-03-23,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure effective,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"

### Task 1.7: Advanced Filtering with .loc[]

Use `.loc[]` to create a DataFrame that shows only the `company`, `jobs_cut`, and `ceo_quote` columns for companies where:
- The percentage of workforce cut is greater than or equal to 10%
- The stock reaction was "Positive"

This will help us see what CEOs said when making significant cuts that the market rewarded.

*Hint: `.loc[row_condition, ['col1', 'col2']]` lets you filter rows and select columns simultaneously*

In [ ]:
# Use .loc to filter rows and select columns
layoffs.loc[((layoffs['pct_workforce_cut'] >= 10) & (layoffs['stock_reaction'] == 'Positive')),['company', 'jobs_cut', 'ceo_quote']]

,company,jobs_cut,ceo_quote
1,Block,4000,Smaller team using AI can do more
2,Meta Reality Labs,1500,Redirecting investment toward AI R&D
3,Atlassian,1600,Bar for great software companies has gone up
4,Oracle,30000,Swapping workers for AI chips
9,Ericsson,1600,Operational efficiency initiatives
11,ams OSRAM,2000,Restructuring to improve profitability
13,WiseTech Global,2000,AI tools handle testing workflows
26,Meta Platforms (Planned),16000,Building personal superintelligence

## Part 2: Basic Analysis Tasks

Now that you understand the data structure and can filter/manipulate DataFrames, let's extract meaningful insights.

### Task 2.1: Unique Sectors

Get a list of all unique sectors represented in the layoff data. How many different sectors are there?

*Hint: Use `.unique()` or `.nunique()` on the appropriate column*

In [ ]:
# Find unique sectors
unique_sectors = layoffs['sector'].unique()
print(f"Number of unique sectors: {layoffs['sector'].nunique()}")
print(f"\nSectors: {sorted(unique_sectors)}")

Number of unique sectors: 23

Sectors: ['AI Research', 'Automotive Tech', 'CRM/SaaS', 'Cybersecurity', 'Design Software', 'E-Commerce', 'E-Commerce/Cloud', 'EV Batteries', 'Enterprise SaaS', 'Enterprise Software', 'Fintech', 'Grocery Tech', 'Insurance', 'Interior Design Tech', 'Logistics Software', 'Manufacturing', 'Networking/Cybersecurity', 'Retail Pharmacy', 'Semiconductors', 'Social Media', 'Social Media/AI', 'Social Media/VR', 'Telecommunications']

### Task 2.2: Jobs Cut by Country

Group the data by country and calculate the total number of jobs cut in each country. Which country has experienced the most layoffs? Sort your results in descending order.

*Hint: Use `.groupby()` with `.sum()` or `.agg()`, then sort with `.sort_values()`*

In [ ]:
# Group by country and aggregate jobs cut

layoffs.groupby('country').sum().sort_values('country', ascending=False)

#layoffs.groupby('country').agg({'jobs_cut': 'sum'}).sort_values('country', ascending=False).reset_index() #This gives the same result with just the columns of interest. Uncomment it to try it out!

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,pre_layoff_headcount,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
country,,,,,,,,,,,,,,,,,,,,,
USA,AmazonBlockMeta Reality LabsOracleSalesforceAu...,2026-01-152026-02-282026-01-202026-02-012026-0...,83046,166.5,E-Commerce/CloudFintechSocial Media/VREnterpri...,SeattleSan FranciscoMenlo ParkAustinSan Franci...,9,Reduce bureaucracy and management layersAI too...,1660.7,2682566,...,23450,45650,CNBC / NetworkWorldCNBC / CrunchbaseInformatio...,January 2026February 2026January 2026February ...,Q1 2026Q1 2026Q1 2026Q1 2026Q1 2026Q1 2026Q1 2...,North AmericaNorth AmericaNorth AmericaNorth A...,Mega (5K+)Large (2K-5K)Medium (500-2K)Mega (5K...,PositivePositivePositivePositivePositivePositi...,173.92,"March 18, 2026March 18, 2026March 18, 2026Marc..."
UK,Ocado,2026-01-30,1000,7.0,Grocery Tech,Hatfield,1,AI automation in warehouse operations,3.8,14000,...,0,0,NetworkWorld,January 2026,Q1 2026,Europe,Medium (500-2K),Positive,7.14,"March 18, 2026"
Sweden,Ericsson,2026-01-15,1600,12.0,Telecommunications,Stockholm,0,Declining 5G demand and cost reduction,24.3,105000,...,3000,5000,InformationWeek / FierceNetwork,January 2026,Q1 2026,Europe,Medium (500-2K),Positive,1.52,"March 18, 2026"
Spain,Telefonica,2026-01-15,5000,5.0,Telecommunications,Madrid,0,Cost restructuring with compensation,44.5,100000,...,0,3000,FierceNetwork,January 2026,Q1 2026,Europe,Large (2K-5K),Positive,5.00,"March 18, 2026"
Netherlands,ASML,2026-01-20,1700,3.4,Semiconductors,Veldhoven,0,Chip market slowdown,30.8,42000,...,0,0,NetworkWorld,January 2026,Q1 2026,Europe,Medium (500-2K),Negative,4.05,"March 18, 2026"
India,Livspace,2026-02-10,1000,15.0,Interior Design Tech,Bangalore,1,AI design tools replace human designers,0.3,7000,...,0,0,Medha Cloud,February 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Neutral,14.29,"March 18, 2026"
Germany,Ergo Insurance,2026-03-01,200,2.0,Insurance,Dusseldorf,1,AI automates insurance tasks,0.0,9000,...,0,0,Intellizence,March 2026,Q1 2026,Europe,Small (<500),Neutral,2.22,"March 18, 2026"
Canada,Algoma SteelAlgoma Steel,2026-03-072026-03-23,2000,40.0,ManufacturingManufacturing,Sault Ste MarieSault Ste Marie,0,Blast furnace closureBlast furnace closure eff...,5.6,10000,...,0,0,IntellizenceIntellizence,March 2026March 2026,Q1 2026Q1 2026,North AmericaNorth America,Medium (500-2K)Medium (500-2K),NegativeNegative,40.00,"March 18, 2026March 18, 2026"
Austria,ams OSRAM,2026-02-05,2000,12.0,Semiconductors,Premstaetten,0,Cost restructuring and portfolio focus,3.2,21000,...,0,500,NetworkWorld,February 2026,Q1 2026,Europe,Medium (500-2K),Positive,9.52,"March 18, 2026"
Australia,AtlassianWiseTech Global,2026-03-142026-02-20,3600,35.0,Enterprise SoftwareLogistics Software,SydneySydney,2,Pivot to AI-first company strategyAI replaces ...,8.3,24000,...,0,500,TechRepublic / MetaintroMedha Cloud,March 2026February 2026,Q1 2026Q1 2026,Asia-PacificAsia-Pacific,Medium (500-2K)Medium (500-2K),PositivePositive,35.00,"March 18, 2026March 18, 2026"

### Task 2.3: Calculate Total Original Workforce

The dataset includes `jobs_cut` and `pct_workforce_cut` columns. Create a new column called `calculated_original_workforce` that estimates the original workforce size before layoffs.

**Formula:** If X jobs were cut and that represents Y% of the workforce, then the original workforce = `jobs_cut / (pct_workforce_cut / 100)`

Compare your calculated values with the `pre_layoff_headcount` column. How close are they?

<details>
  <summary>Click to see spoiler</summary>
  There should be some differences because of the inconsistent rounding of our originial dataseet as well as the possible rounding of the percentage of workforce cut when reporting
</details>

*Hint: Create new columns using bracket notation like `df['new_column'] = calculation`*

In [ ]:
# Create the calculated_original_workforce column
layoffs['calculated_original_workforce'] = layoffs['jobs_cut'] / layoffs['pct_workforce_cut']

# Compare with pre_layoff_headcount (optional: calculate difference or view both columns)
# layoffs['calc_diff'] = layoffs['calculated_original_workforce'] - layoffs['pre_layoff_headcount']

### Task 2.4: Categorize Companies by Revenue

Create a new column called `revenue_category` that classifies companies into revenue brackets based on their 2025 revenue (`company_revenue_2025_bn`).

First, explore the revenue distribution to determine reasonable category boundaries. Then create categories that make sense for the data.

*Hint: Look at the min, max, and quartiles of the revenue column. Consider using `pd.cut()` to create categorical bins*

In [ ]:
# First, explore the revenue distribution
layoffs['company_revenue_2025_bn'].describe()

count     28.00000
mean      63.62500
std      139.44986
min        0.00000
25%        3.50000
50%        9.40000
75%       53.90000
max      716.90000
Name: company_revenue_2025_bn, dtype: float64

In [ ]:
# Create revenue_category column with appropriate bins
# Suggested categories: 'Startup/Small', 'Mid-Market', 'Large Enterprise', 'Mega-Corp'

rev_bins = [0, 50, 100, 500, 1000] # You can change the bins to whatever sizes you want. As long as the number of intervals is the same as your label count
rev_labels = ['Startup/Small', 'Mid-Market', 'Large Enterprise', 'Mega-Corp']
layoffs['revenue_category'] = pd.cut(layoffs['company_revenue_2025_bn'], bins=rev_bins, labels=rev_labels)
layoffs[['company','revenue_category']].head(5)

             company  revenue_category
0             Amazon         Mega-Corp
1              Block     Startup/Small
2  Meta Reality Labs  Large Enterprise
3          Atlassian     Startup/Small
4             Oracle        Mid-Market

### Task 2.5: Revenue and AI-Cited Layoffs

Investigate whether there's a relationship between company revenue and whether AI was cited as an explicit reason for layoffs.

Questions to explore:
- What's the average revenue of companies that cited AI vs. those that didn't?
- What percentage of companies in each revenue category cited AI?

*Hint: Use `.groupby()` with the `ai_cited` column, and consider using `.mean()` or `.value_counts()` with normalization*

In [ ]:
# Analyze relationship between revenue and AI being cited
layoffs[['company_revenue_2025_bn', 'revenue_category', 'ai_cited']].groupby(['revenue_category', 'ai_cited']).mean()

/tmp/ipykernel_31852/3548303163.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  layoffs[['company_revenue_2025_bn', 'revenue_category', 'ai_cited']].groupby(['revenue_category', 'ai_cited']).mean()

                           company_revenue_2025_bn
revenue_category ai_cited
Startup/Small    False                   14.522222
                 True                    10.566667
Mid-Market       False                   68.450000
                 True                    52.900000
Large Enterprise False                  160.000000
                 True                   164.500000
Mega-Corp        False                  716.900000
                 True                          NaN

## Part 3: Challenge Tasks

These tasks require more complex operations and critical thinking. You'll need to combine multiple pandas techniques.

### Challenge 3.1: Monthly Layoff Trends

Create an ordered list showing the total jobs cut by month in descending order. Which month saw the most significant layoffs?

Bonus: Also show the number of layoff events (count of companies) per month alongside total jobs cut.

In [ ]:
# Jobs cut by month in descending order

<details>
<summary>
Click to reveal possible solution
</summary>
Copy and paste this to see what the solution should look like. If you get something similar, then good job!

```
layoffs.groupby('month').agg({'jobs_cut':'sum'}).sort_values('jobs_cut',ascending=False)
```
</details>

### Challenge 3.2: Workforce Size Categories

Create a new column called `workforce_size_category` that categorizes companies based on their pre-layoff headcount.

Use these categories:
- **Small:** < 10,000 employees
- **Medium:** 10,000 - 49,999 employees
- **Large:** 50,000 - 99,999 employees
- **Mega:** 100,000+ employees

After creating the categories, analyze: Which workforce size category experienced the highest total job cuts?

In [ ]:
# Create workforce_size_category column

<details>
<summary>
Click to reveal possible solution
</summary>
Copy and paste this to see what the solution should look like. If you get something similar, then good job!

```
work_bins = [0, 10000, 50000, 100000, 1000000] #
work_labels = ['Small', 'Medium', 'Large', 'Mega']
layoffs['workforce_size_category'] = pd.cut(layoffs['pre_layoff_headcount'], bins=work_bins, labels=work_labels)
layoffs[['company', 'workforce_size_category']]
```
</details>

### Challenge 3.3: Company Size and AI Citations

Investigate whether there's a correlation between company size (workforce) and whether AI was cited as the explicit reason for layoffs.

Questions to explore:
- What percentage of companies in each workforce size category cited AI?
- Is there a pattern? Are larger or smaller companies more likely to cite AI?
- What's the average workforce size for companies that cited AI vs. those that didn't?

In [ ]:
# Analyze relationship between company size and AI being cited

<details>
<summary>
Click to reveal possible solution
</summary>

```
df = layoffs.groupby(['workforce_size_category'])['ai_cited'].value_counts(normalize=True)
```

</details>

### Challenge 3.4: Efficiency Ratio Analysis

Create a new column called `workforce_revenue_ratio` that calculates the number of employees per billion dollars of revenue.

**Formula:** `pre_layoff_headcount / company_revenue_2025_bn`

This ratio indicates how "employee-intensive" a company is relative to its revenue.

After creating this column:
- Which companies have the highest and lowest ratios?
- Is there any relationship between this ratio and whether a company cited AI as a reason?
- What might a high vs. low ratio tell you about a company's business model?

**Note:** Be careful with companies that have 0 revenue (like startups). You may need to handle these specially.

In [ ]:
# Create workforce_revenue_ratio column
# Handle edge cases (companies with 0 or very low revenue)

<details>
<summary>
Click to reveal possible solution
</summary>

```
layoffs['workforce_revenue_ratio'] = layoffs['pre_layoff_headcount'] / (layoffs['company_revenue_2025_bn']).layoffs(df['company_revenue_2025_bn'] == 0)
```

Normally, we would discuss how to handle 0 edge cases, but if we don't have one established, just have a rationale for why you handled it the way you did. (Great minor interview prep skill for a scenario where the 'customer' does not specify how to handle an edge case after you attempt to get clarification)

In this case, technically speaking, there was no reported revenue, at least on the scale of billions of dollars, so a valid idea might be the company is a startup 'pre-revenue', hence NaN.

</details>

## Part 4: Reflection and Insights

Based on your analysis, answer the following questions in the markdown cells below:

### Question 1: AI Impact

What patterns did you observe regarding AI being cited as a reason for layoffs? Are certain types of companies (by size, revenue, or sector) more likely to cite AI?

*Double-click to edit and write your answer here*

### Question 2: Geographic Patterns

Which countries or regions were most affected by layoffs? What might explain these geographic patterns?

*Double-click to edit and write your answer here*

### Question 3: Surprising Findings

What was the most surprising or interesting insight you discovered in this data? What additional analysis would you want to conduct if you had more time?

*Double-click to edit and write your answer here*

## Bonus: Open-Ended Exploration

Use the cells below to explore any additional questions or patterns that interest you in the data. Some ideas:
- Analyze the `sector` column for industry-specific trends
- Investigate the `stock_reaction` column to see market responses
- Examine the relationship between percentage of workforce cut and company performance
- Compare companies that had layoffs in 2024/2025 vs. first-time layoffs in 2026

In [ ]:
# Your open-ended exploration here